[PLUGIN-924] update display names for DLP plugins
data-integrations/dlp-plugins pull request #41
Opened 2022-01-10 16:23 UTC by itsankit-google

[PLUGIN-924](https://cdap.atlassian.net/browse/PLUGIN-924)

2022-01-10 19:05 UTC, bdmogal requested changes
These changes look good. Can you also please update the description per the Jira?

2022-01-10 21:55 UTC, avirmani approved these changes

2022-01-11 04:22 UTC, itsankit-google commented
> These changes look good. Can you also please update the description per the Jira?

I did verified that the description already looks the same what JIRA suggests, https://github.com/data-integrations/dlp-plugins/blob/develop/docs/SensitiveRecordDecrypt-transform.md#description

2022-01-12 16:49 UTC, bdmogal approved these changes

2022-01-12 16:50 UTC, merged